# Generated by Django 5.0.3 on 2024-03-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_art',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated_art',
            new_name='updated_at',
        ),
    ]
